/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class Point {
  /**
   * X-coordinate.
   */
  x: number;

  /**
   * Y-coordinate.
   */
  y: number;

  /**
   * Constructor.
   * @param x
   * @param y
   */
  constructor(x: number, y: number) {
    this.x = x;
    this.y = y;
  }

  /**
   * Set value.
   * @param x
   * @param y
   */
  set(x: number, y: number): void {
    this.x = x;
    this.y = y;
  }
}