/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for all features.
 */
export class CommonConstants {
  /**
   * animation duration of content switching.
   */
  static readonly DURATION_ADS = 200;
  /**
   * Height of head portrait.
   */
  static readonly HEIGHT_HEAD = 40;
  /**
   * Height of carousel title.
   */
  static readonly HEIGHT_CAROUSEL_TITLE = 90;
  /**
   * Font size of tab page which content has only tab name.
   */
  static readonly FONT_SIZE_PAGE_CONTENT = 28;
  /**
   * Thinner font.
   */
  static readonly FONT_WEIGHT_LIGHT = 400;
  /**
   * Normal font.
   */
  static readonly FONT_WEIGHT_NORMAL = 500;
  /**
   * Bold font.
   */
  static readonly FONT_WEIGHT_BOLD = 700;
  /**
   * Page layout weight.
   */
  static readonly LAYOUT_WEIGHT = 1;
  /**
   * Border angle.
   */
  static readonly BORDER_RADIUS = 12;
  /**
   * Line height for more.
   */
  static readonly LINE_HEIGHT_MORE = 19;
  /**
   * Line height for navigation.
   */
  static readonly LINE_HEIGHT_NAVIGATION = 28;
  /**
   * Space of topBar.
   */
  static readonly SPACE_TOP_BAR = 16;
  /**
   * Space of navigation.
   */
  static readonly SPACE_NAVIGATION = 8;
  /**
   * Border width of head portrait.
   */
  static readonly WIDTH_HEAD_BORDER = 2;
  /**
   * Width of head portrait.
   */
  static readonly WIDTH_HEAD = 40;
  /**
   * Radius of head portrait.
   */
  static readonly RADIUS_HEAD = 20;
  /**
   * Rolling duration.
   */
  static readonly SWIPER_TIME = 1500;
  /**
   * Margin of play page.
   */
  static readonly MARGIN_PLAY_PAGE = 10;
  /**
   * Margin of text bottom.
   */
  static readonly BOTTOM_TEXT = 4;
  /**
   * Margin of banner top.
   */
  static readonly TOP_ADS = 12;
  /**
   * Margin of navigation left.
   */
  static readonly LEFT_NAVIGATION = 20;
  /**
   * Margin of banner left.
   */
  static readonly ADS_LEFT = 12;
  /**
   * Top margin of picture name.
   */
  static readonly TOP_NAME = 8;
  /**
   * Top margin of picture description.
   */
  static readonly TOP_DESCRIPTION = 4;
  /**
   * Top margin of vote icon.
   */
  static readonly TOP_IMAGE_VOTE = 20;
  /**
   * Top margin of head portrait.
   */
  static readonly TOP_HEAD = 40;
  /**
   * Maximum width.
   */
  static readonly FULL_WIDTH = '100%';
  /**
   * Maximum height.
   */
  static readonly FULL_HEIGHT = '100%';
  /**
   * Width of play model.
   */
  static readonly WIDTH_PLAY = '95%';
  /**
   * Width of tab page.
   */
  static readonly PAGE_WIDTH = '94.4%';
  /**
   * Width of sort name.
   */
  static readonly WIDTH_SORT_NAME = '62.2%';
  /**
   * Sort content width of all.
   */
  static readonly WIDTH_SORT = '92%';
  /**
   * Sort content width of movie.
   */
  static readonly WIDTH_MOVIE_SORT = '90%';
  /**
   * Width of picture.
   */
  static readonly WIDTH_PICTURE = '72%';
  /**
   * Height of banner.
   */
  static readonly HEIGHT_BANNER = '27%';
  /**
   * Width of vote icon.
   */
  static readonly WIDTH_VOTE = '8.9%';
  /**
   * Width of back icon.
   */
  static readonly WIDTH_BACK_ICON = '6.7%';
  /**
   * Top margin of sort.
   */
  static readonly MARGIN_TOP_SORT = '3.2%';
  /**
   * Bottom margin of sort.
   */
  static readonly MARGIN_BOTTOM_SORT = '1.7%';
  /**
   * Bottom margin of grid.
   */
  static readonly MARGIN_BOTTOM_GRID = '4.2%';
  /**
   * Height of video.
   */
  static readonly WIDTH_VIDEO = '26.2%';
  /**
   * Number of columns.
   */
  static readonly TWO_COLUMNS = '1fr 1fr';
  /**
   * Number of rows.
   */
  static readonly TWO_ROWS = '1fr 1fr';
  /**
   * Number of columns.
   */
  static readonly THREE_COLUMNS = '1fr 1fr 1fr';
  /**
   * Number of rows.
   */
  static readonly THREE_ROWS = '1fr 1fr 1fr';
  /**
   * Gap of columns.
   */
  static readonly GAP_COLUMNS = '2.2%';
  /**
   * Height of grid.
   */
  static readonly HEIGHT_GRID = '45%';
  /**
   * Height of movie description.
   */
  static readonly HEIGHT_DESCRIPTION = '12.3%';
  /**
   * Height of top bar.
   */
  static readonly TOP_BAR_HEIGHT = '7.2%';
  /**
   * Height of comment icon.
   */
  static readonly HEIGHT_COMMENT = '4.1%';
  /**
   * Height of back icon.
   */
  static readonly HEIGHT_BACK_ICON = '3.1%';
  /**
   * Horizontal position of comment.
   */
  static readonly OFFSET_COMMENT_X = '-5%';
  /**
   * Vertical position of comment.
   */
  static readonly OFFSET_COMMENT_Y = '10%';
  /**
   * Vertical position of description.
   */
  static readonly OFFSET_DESCRIPTION_Y = '45%';
  /**
   * Start position.
   */
  static readonly START_POSITION = '0%';
  /**
   * Video play page.
   */
  static readonly PLAY_PAGE = 'pages/PageVideo';
  /**
   * Home page.
   */
  static readonly HOME_PAGE = 'pages/SwiperIndex';
}