export class Constants {
  static readonly DB_NAME = 'e-commerce.db';
  static readonly DB_VERSION = 1;

  static readonly TABLE_USER = 'user';
  static readonly TABLE_PRODUCT = 'product';
  static readonly TABLE_CART = 'cart';
  static readonly TABLE_ADDRESS = 'address';
  static readonly TABLE_ORDER = 'orders';
  static readonly TABLE_ORDER_ITEM = 'order_item';
  static readonly TABLE_FAVORITE = 'favorite';
  static readonly TABLE_FOOTPRINT = 'footprint';

  static readonly KEY_USER_SESSION = 'user_session';
}