/*
 * Copyright (c) 2023 Your Company Name
 * All rights reserved.
 *
 * Licensed under the Apache License, Version2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://.apache.org/licenses/LICENSE-2.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS * WITHOUT WARRANTIES OR CONDITIONS OF ANY, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Copyright [年份] [版权所有者]
 * 保留所有权利
 */
import localUnitTest from './LocalUnit.test';

export default function testsuite() {
  localUnitTest();
}