/*
 * Copyright (c) 2026 CoinNote. All rights reserved.
 * This software is the confidential and proprietary information of Your.
 * You shall not disclose such Confidential Information and shall use it in accordance with the terms of the license agreement you entered into with YourCompany.
 */
// SPDX-License-Identifier: Apache-2.0
import localUnitTest from './LocalUnit.test';

export default function testsuite() {
  localUnitTest();
}